### ISSUE TITLE
Problemas de segurança

### ISSUE THREAD

**Issue by Gabriel-Tapes** [luisviniciuslv/api_eco_de_palavras#2]
Olhando o projeto encontrei dois problemas de segurança, que podem se tornar uma dor de cabeça, mas que podem ser facilmente resolvidos:

### Host de produção hard coded:

No arquivo static/script.js, na requisição POST feito pela fetch api, o host de produção é colocado hard coded. Isso pode se tornar um problema caso
- Em algum momento seja trocada a hospedagem do projeto
- para testar em localhost
- para escalar a aplicação

A melhor solução seria fazer post para '/', pois não é necessário o hostname e a porta caso as rotas da aplicação sejam as mesmas do frontend, assim poderia utilizar qualquer hostname mudando em apenas um lugar, algo que melhora a segurança e escalabilidade da aplicação.

### Code injection:

Atualmente a publicação tem a vulnerabilidade de code injection, onde é possível executar scripts no lado do cliente, pois é possível adicionar html nas mensagens, a demonstração está [nesse comentário](https://www.tabnews.com.br/Katsudouki/84678335-1ed2-4964-910d-d629237f70d1).

Uma solução simples para esse problema seria sanitizar os textos recebidos, então temos algumas possibilidades:

- ao receber uma mensagem eliminar os caracteres < e >
- eliminar a string "<script"

Na primeira possibilidade não seria possível passar html para o programa, o que implicaria na impossibilidade de imagens, vídeos, links e etc fazerem parte da mensagem. Acredito que o intuíto da aplicação seria apenas texto, então acredito que seria uma solução viável. 
Já a segunda possibilidade manteria possível adicionar imagens, vídeos, links e etc, mas excluiria qualquer tag script que fizesse parte da mensagem.

Existem soluções melhores e mais seguras, mas as que propus já resolveriam a maior parte dos problemas de segurança que a aplicação possui.

**Comment by Gabriel-Tapes** [comment]
Há outro erro também, nas rotas da aplicação.

`routes.py`:

```python
routes = Routes(static_path='static')
...
@routes.get('/post')
async def index(req: Request, res: Response):
  res.render_page('./static/index.html').status(200).send()
```

Esse código gera o seguinte erro, pelo menos em localhost:

```shell
Traceback (most recent call last):
  File "/home/tapes-arch/.local/lib/python3.10/site-packages/PyForgeAPI/classes/handler.py", line 49, in handle_request
    await self.routes[path][method](Request(self), Response(self))
  File "/home/tapes-arch/Repositories/api_eco_de_palavras/routes/routes.py", line 9, in index
    res.render_page('./static/index.html').status(200).send()
  File "/home/tapes-arch/.local/lib/python3.10/site-packages/PyForgeAPI/classes/response.py", line 80, in render_page
    with io.open(f"{path}", 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'static/./static/index.html'
```

Isso ocorre pois quando você atribui um static_path, o valor que você atribui é colocado como um prefixo para os arquivos estáticos, portanto, o erro é causado pois adiciona o prefico 'static' ao caminho fornecido, ficando 'static/.static/index.html'. Para evitar esse erro basta colocar apenas o nome do arquivo, ou da subpasta que está o arquivo.

Irei fazer um pull request resolvendo todos os problemas que citei nessa issue.
